name: Issues Form
description: Use the template to report a bug, request a feature, or suggest an enhancement.
title: "[Issue] <short summary>"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        **Title format:**  
        Use short, descriptive titles with a component tag.  
        Example: `[map view] Earthquakes are not shown`
  
  - type: dropdown
    id: issue_type
    attributes:
      label: Type
      options:
        - Bug
        - Feature Request
        - Enhancement
        - Documentation
        - Question
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: "Add relevant details, steps to reproduce, expected outcome etc. You can upload the logs / screenshots."

  - type: input
    id: environment
    attributes:
      label: Environment (optional)
      description: OS, browser, or deployment type (e.g., macOS, Docker, etc.)