name: Publish image update status
on:
  schedule: [ { cron: "*/15 * * * *" } ]  # every 15 minutes
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Check your two images/tags
      - name: Check backend image
        id: be
        uses: cloudposse/actions/docker-image-update-checker@main
        with:
          image: ghcr.io/eewpw/eewpw-backend
          tag: master

      - name: Check frontend image
        id: fe
        uses: cloudposse/actions/docker-image-update-checker@main
        with:
          image: ghcr.io/eewpw/eewpw-dashboard
          tag: master

      - name: Write status JSON
        run: |
          mkdir -p public
          jq -n --arg be_dig "${{ steps.be.outputs.digest }}" \
                --arg fe_dig "${{ steps.fe.outputs.digest }}" \
                --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            '{backend:{digest:$be_dig}, frontend:{digest:$fe_dig}, updated:$ts}' \
            > public/update.json

      # Commit the JSON back to the repo (default branch) OR publish to Pages
      - name: Commit update.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/update.json
          git commit -m "chore: update image digests [skip ci]" || echo "no changes"
          git push