name: Publish image update status

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # --- GHCR digests (public images -> anonymous token is enough) ---
      - name: Get backend digest from GHCR
        id: be
        env:
          REPO: eewpw/eewpw-backend
        run: |
          set -e
          # Anonymous token (works for public images)
          TOKEN=$(curl -fsSL "https://ghcr.io/token?service=ghcr.io&scope=repository:${REPO}:pull" | jq -r .token)
          # 1) List tags (diagnostic)
          TAGS_JSON=$(curl -fsSL -H "Authorization: Bearer $TOKEN" "https://ghcr.io/v2/${REPO}/tags/list")
          echo "Backend tags JSON: $TAGS_JSON"
          # 2) Pick a tag
          PREF=$(echo "$TAGS_JSON" | jq -r '.tags // [] | map(select(. == "master" or . == "main" or . == "latest")) | .[0]')
          if [ -z "$PREF" ] || [ "$PREF" = "null" ]; then
            # fallback to first available tag, if any
            PREF=$(echo "$TAGS_JSON" | jq -r '.tags // [] | .[0]')
          fi
          if [ -z "$PREF" ] || [ "$PREF" = "null" ]; then
            echo "No tags found for ${REPO}. Check GHCR package visibility and name."; exit 1
          fi
          echo "Selected backend tag: $PREF"
          # 3) Fetch digest
          HEADERS=$(mktemp)
          HTTP=$(curl -s -o /dev/null -w "%{http_code}" -I \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.v2+json" \
            -D "$HEADERS" "https://ghcr.io/v2/${REPO}/manifests/${PREF}")
          echo "Backend manifest HTTP: $HTTP"
          DIGEST=$(grep -i '^Docker-Content-Digest:' "$HEADERS" | awk '{print $2}' | tr -d '\r')
          echo "Backend digest: $DIGEST"
          test -n "$DIGEST" || (echo "No backend digest for ${REPO}:${PREF}"; exit 1)
          echo "tag=$PREF" >> "$GITHUB_OUTPUT"
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
          
      - name: Get frontend digest from GHCR
        id: fe
        env:
          REPO: eewpw/eewpw-dashboard
        run: |
          set -e
          TOKEN=$(curl -fsSL "https://ghcr.io/token?service=ghcr.io&scope=repository:${REPO}:pull" | jq -r .token)
          TAGS_JSON=$(curl -fsSL -H "Authorization: Bearer $TOKEN" "https://ghcr.io/v2/${REPO}/tags/list")
          echo "Frontend tags JSON: $TAGS_JSON"
          PREF=$(echo "$TAGS_JSON" | jq -r '.tags // [] | map(select(. == "master" or . == "main" or . == "latest")) | .[0]')
          if [ -z "$PREF" ] || [ "$PREF" = "null" ]; then
            PREF=$(echo "$TAGS_JSON" | jq -r '.tags // [] | .[0]')
          fi
          if [ -z "$PREF" ] || [ "$PREF" = "null" ]; then
            echo "No tags found for ${REPO}. Check GHCR package visibility and name."; exit 1
          fi
          echo "Selected frontend tag: $PREF"
          HEADERS=$(mktemp)
          HTTP=$(curl -s -o /dev/null -w "%{http_code}" -I \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.v2+json" \
            -D "$HEADERS" "https://ghcr.io/v2/${REPO}/manifests/${PREF}")
          echo "Frontend manifest HTTP: $HTTP"
          DIGEST=$(grep -i '^Docker-Content-Digest:' "$HEADERS" | awk '{print $2}' | tr -d '\r')
          echo "Frontend digest: $DIGEST"
          test -n "$DIGEST" || (echo "No frontend digest for ${REPO}:${PREF}"; exit 1)
          echo "tag=$PREF" >> "$GITHUB_OUTPUT"
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
          
      - name: Compute new status JSON
        id: buildjson
        run: |
          NEW_BE="${{ steps.be.outputs.digest }}"
          NEW_FE="${{ steps.fe.outputs.digest }}"
          TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          if [ -f update.json ]; then
            FILE_EXISTS=true
            OLD_BE=$(jq -r '.backend.digest // empty' update.json)
            OLD_FE=$(jq -r '.frontend.digest // empty' update.json)
          else
            FILE_EXISTS=false
            OLD_BE=""; OLD_FE=""
          fi
          echo "file_exists=$FILE_EXISTS" >> $GITHUB_OUTPUT
          echo "old_be=$OLD_BE" >> $GITHUB_OUTPUT
          echo "old_fe=$OLD_FE" >> $GITHUB_OUTPUT
          echo "new_be=$NEW_BE" >> $GITHUB_OUTPUT
          echo "new_fe=$NEW_FE" >> $GITHUB_OUTPUT
          jq -n --arg be "$NEW_BE" --arg fe "$NEW_FE" --arg ts "$TS" \
            '{backend:{digest:$be}, frontend:{digest:$fe}, updated:$ts}' > update.new.json

      - name: Create or update file
        if: steps.buildjson.outputs.file_exists == 'false' || steps.buildjson.outputs.old_be != steps.buildjson.outputs.new_be || steps.buildjson.outputs.old_fe != steps.buildjson.outputs.new_fe
        run: |
          mv update.new.json update.json
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add update.json
          git commit -m "chore: update image digests [skip ci]" || echo "no changes"
          git push

      - name: Skip update (no digest change)
        if: steps.buildjson.outputs.file_exists == 'true' && steps.buildjson.outputs.old_be == steps.buildjson.outputs.new_be && steps.buildjson.outputs.old_fe == steps.buildjson.outputs.new_fe
        run: echo "No digest change; not committing."
